### ISSUE TITLE
Hibernate SchemaUpdate run-time error

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#10]
Hibernate tries to add existing columns/keys to "location" table at application start.
Same issue posted to [StackOverflow](http://stackoverflow.com/questions/1345594/hibernate-schema-update-error).

The error is:
`[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column code varchar(255)
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "code" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column kml text
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "kml" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column protect boolean default false not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "protect" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column update_date date not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "update_date" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column user_id int8
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "user_id" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column code_type_id int8 not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "code_type_id" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column gis_src_id int8 not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "gis_src_id" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column location_type_id serial not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "location_type_id" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add column parent_gid int8
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "parent_gid" of relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location_type add column name varchar(255)
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "name" of relation "location_type" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location_type add column user_definable boolean default false not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "user_definable" of relation "location_type" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location_type add column composed_of_id integer
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "composed_of_id" of relation "location_type" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location_type add column super_type_id serial not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "super_type_id" of relation "location_type" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table super_type add column user_definable boolean default false not null
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: column "user_definable" of relation "super_type" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add constraint FK_1xy18vee7xaabypaj3n5jqee foreign key (code_type_id) references code_type
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: constraint "fk_1xy18vee7xaabypaj3n5jqee" for relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add constraint FK_ccwo5xt7c67ngolc8x52ktb4f foreign key (gis_src_id) references gis_src
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: constraint "fk_ccwo5xt7c67ngolc8x52ktb4f" for relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add constraint FK_a37gs5po1sy9eyx3ahh4q319h foreign key (location_type_id) references location_type
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: constraint "fk_a37gs5po1sy9eyx3ahh4q319h" for relation "location" already exists
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: alter table location add constraint FK_rulncca31o3ukf0sc9a1m8bx0 foreign key (parent_gid) references location
[error] - org.hibernate.tool.hbm2ddl.SchemaUpdate - ERROR: constraint "fk_rulncca31o3ukf0sc9a1m8bx0" for relation "location" already exists`

**Comment by Amin-Tajgardoon** [comment]
I experience the same error but for ALL tables, not only for "location" table

**Comment by Amin-Tajgardoon** [comment]
adding the default_schema in persistence.xml solved the problem for me (so far):
`<property name="hibernate.default_schema" value="public" />`

**Comment by sahawut** [comment]
Your solution is good even if it might not solve the problem. I think you should commit the change.

**Comment by Amin-Tajgardoon** [comment]
fix in commit:
https://github.com/midas-isg/ls/pull/23/commits/55596abe6fb5c8f8e5e16ae5cb130069895a7308

sent pull_request
