### ISSUE TITLE
LS cache-initialization slows down the first name-search when application restarts

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#11]
This issue slows down the development process because of the delay introduced at each application restart.

**Comment by Amin-Tajgardoon** [comment]
We decided to fix this issue in version 2.

**Comment by Amin-Tajgardoon** [comment]
Sahawut noted the search performance might be acceptable even without using any cached information.

**Comment by Amin-Tajgardoon** [comment]
It takes me more than 3 minutes to initialize cache

**Comment by Amin-Tajgardoon** [comment]
fixed in commit:
https://github.com/midas-isg/ls/pull/24/commits/ab7f3776578ab9b2e7fb7fc11b5041f6604ee476

**Comment by Amin-Tajgardoon** [comment]
What is the reason for reopening this issue? @TerenceSperringerJr

**Comment by TerenceSperringerJr** [comment]
This might be a separate issue actually, but sometimes when rebuilding .scala.html template files play goes into a seemingly infinite loop and the output reads:

"updating cache ..."

I've had this happen 4 times this morning, and I'll post the full output the next time it occurs.

**Comment by Amin-Tajgardoon** [comment]
@TerenceSperringerJr If it happened again, please open a new issue with a relevant title.
