### ISSUE TITLE
Unify parameters about fields used in GET and POST requests

### ISSUE THREAD

**Issue by sahawut** [midas-isg/ls#14]
Parameters about fields used in GET and POST requests have been used inconstantly. Some are used as boolean which will soon be too many to manage. We should unify them.

Here are my suggestion how to unify them:
Common parameters for included, excluded and expanded fields sorted by order of execution:
1. _onlyFields: include only the provided fields in the response.
2. _excludedFields: exclude all the provided fields in the response.
3. _expandedFields: expand information of the resources all the provided collection fields in the response.

Format of the above parameter:
- Fields are separated comma; e.g features,properties
- Subfields are enclosed in parentheses and separated by comma; e.g. features(geometry,properties(children))
- If we need to distinguish between objects and arrays, here is a more restrict format of the above example: features[{geometry,properties{children}}]

At the time of creating this issue, I was editing a document called "Guide for ReST API Design via HTTP" capturing knowledge about ReST via HTTP. The above suggestion is a part of the document. Here is the link: https://docs.google.com/document/d/1j_QIhwlEJTrn-VmMzpVTUQwW0jLRKqIAFWFsA0qUIOI

**Comment by Amin-Tajgardoon** [comment]
Fixed most APIs in version 2.
Will look better by dropping version 1 parameters.
