### ISSUE TITLE
Search for "Wales [Cymru GB-CYM]" returns no result

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#16]

**Comment by TerenceSperringerJr** [comment]
Unable to reproduce this. It seems to work fine on my branch at least.

**Comment by TerenceSperringerJr** [comment]
Is this still an issue for you?

**Comment by Amin-Tajgardoon** [comment]
It works when front-end tokenizes the search term and requests for each individual token, e.g., "Wales". But still it cannot be found if query just for the whole term.

**Comment by Amin-Tajgardoon** [comment]
The problem is that in preprocessing hyphen is removed from "Wales [Cymru GB-CYM]", but postgresql function to_tsvector() does not.

**Comment by TerenceSperringerJr** [comment]
I think this might be resolved, but I may need to update the endpoint being called to ls/api/locations/find-by-term?_v=2

**Comment by Amin-Tajgardoon** [comment]
The issue resolved as we use the same parser for query terms and names in the database.
