### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#19]
1- Test IntegrationTest.testWithJpaThenRollback fails due to an assumption that specific records always exist in database:
`[error] Test IntegrationTest.testWithJpaThenRollback failed: java.lang.RuntimeException: Cannot find LocationIncluded gid=72676`

2- Test  integrations.server.TestRoutes.allRoutes fails due to timeout. But it passes if run separately using testOnly 

`[error] Test integrations.server.TestRoutes.allRoutes failed: play.libs.F$PromiseTimeoutException: Futures timed out after [30000 milliseconds], took 30.861 sec`

**Comment by Amin-Tajgardoon** [comment]
Methods that fail in IntegrationTest.testWithJpaThenRollback are:
1- testCreateComposite();
2- testFindLocationsByPolygon();

**Comment by sahawut** [comment]
If those test cases just need more time to execute, you may solve by increasing Jasmine time out to be more than 30000 ms for them.

**Comment by Amin-Tajgardoon** [comment]
IntegrationTest.testWithJpaThenRollback does not fail as long as requested location IDs exist in dev db.
integrations.server.TestRoutes.allRoutes passes. Concurrent cach-update solved the problem
