### ISSUE TITLE
bbox missing in find-by-geometry response

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#21]
find-by-geometry with the AuMaridiTown.geojson example as request body does not contain bbox in response.
The reason is that bbox is null

**Comment by Amin-Tajgardoon** [comment]
May need to include request in response too

**Comment by sahawut** [comment]
Do you mean "May need to include bbox in response too"? If so, I think it is OK not to include bbox because bbox is optional in GeoJSON.

**Comment by Amin-Tajgardoon** [comment]
By "May need to include request in response too" I mean put request parameters, i.e., superTypeId and typeId in response.properties, as well as "resultSize". I just added them.

The purpose of this issue is to investigate why bbox is null exactly.

**Comment by sahawut** [comment]
OK.
For resultSize, try to find good term. In the Guide for ReST API Design, currently use 'total'.

See https://docs.google.com/document/d/1j_QIhwlEJTrn-VmMzpVTUQwW0jLRKqIAFWFsA0qUIOI/edit#heading=h.6zhetfng762n.

**Comment by Amin-Tajgardoon** [comment]
Fixed the "missing bbox" problem in version 2, by adding filters to search-APIs
