### ISSUE TITLE
Test Mode RuntimeException at fake-application stop

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#29]
Stopping fake application in Test Mode causes killing the running concurrent processes for the cache and throwing the following exceptions: 
[application-akka.actor.default-dispatcher-x] [TaskInvocation] JPA transaction failed
java.lang.RuntimeException: JPA transaction failed

It does not interfere with the test units, but does not look good!

**Comment by sahawut** [comment]
I'd try not to run the tread for the cache in test cases that the cache is not used at all.

**Comment by Amin-Tajgardoon** [comment]
fixed in commit https://github.com/midas-isg/ls/pull/32/commits/4b1121671f277dd62e70a5e722f885d1f42ff4ea
