### ISSUE TITLE
Index page with Search, Translate, Create menu items

### ISSUE THREAD

**Issue by espinoj** [midas-isg/ls#61]

**Comment by TerenceSperringerJr** [comment]
Isn't this just the navbar?

**Comment by espinoj** [comment]
Yes with updated styling.  Suggest color scheme used by OBC.ide  http://ide.onbc.io/#/

**Comment by TerenceSperringerJr** [comment]
![image](https://user-images.githubusercontent.com/11877847/26888704-d7638794-4b79-11e7-9e25-df1ea705dc23.png)

How about this?

**Comment by espinoj** [comment]
yep looking good
