### ISSUE TITLE
Advanced Search Page

### ISSUE THREAD

**Issue by TerenceSperringerJr** [midas-isg/ls#62]
Make the advanced search page

**Comment by espinoj** [comment]
With either tabs or sections to
Search by name (default page)
Search by code
Search via map

**Comment by TerenceSperringerJr** [comment]
I am assuming you mean "search by filters" rather than only code.
Code translation is a separate, stand-alone feature that has its own page as well.

**Comment by espinoj** [comment]
This "new search page" has search by name/id as default, search via map, advanced search.   For search by ls code we should make that part of search by name.  Should have some code in there so that if someone inputs an only numeric value it directly brings up the location.

**Comment by TerenceSperringerJr** [comment]
Thank you for clarifying; direct access via Apollo Location Code should be pretty easy to implement from just the front-end on the index searchbar (just check input for all numerals and redirect appropriately).

**Comment by TerenceSperringerJr** [comment]
**TODO: Fix UI to be more layman friendly**

**Comment by TerenceSperringerJr** [comment]
subsumed by #104
