### ISSUE TITLE
Support for locations defined by a point and a radius

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/ls#67]
We want to define epidemic zones by giving an XY and Z coordinate and a radius.  This is needed for simulators like Clara that define the epidemic zone as a circle.

Some relevant excerpts from the XSD:
<complexType name="CartesianCircleLocationDefinition">
    <sequence>
      <element name="eastWestOffsetFromCartesianCenter" type="tns:Distance"
               maxOccurs="1" minOccurs="1" />
      <element name="northSouthOffsetFromCartesianCenter" type="tns:Distance"
               maxOccurs="1" minOccurs="1" />
      <element name="altitudeRelativeToCartesianCenter" type="tns:Distance"
               maxOccurs="1" minOccurs="1" />
      <element name="radius" type="tns:Distance" maxOccurs="1"
               minOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="ScenarioCartesianOrigin">
    <sequence>
      <element name="cartesianReferenceLongitude" type="tns:Longitude"
               maxOccurs="1" minOccurs="1" />
      <element name="cartesianReferenceLatitude" type="tns:Latitude"
               maxOccurs="1" minOccurs="1" />
      <element name="cartesianReferenceAltitude" type="tns:Distance"
               maxOccurs="1" minOccurs="1" />
    </sequence>
  </complexType>

 <complexType name="Distance">
    <complexContent>
      <extension base="tns:ParameterValue">
        <sequence>
          <element name="unitOfDistance" type="tns:UnitOfDistanceEnum"
                   maxOccurs="1" minOccurs="1">
          </element>
          <element name="value" type="double" maxOccurs="1"
                   minOccurs="1">
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="UnitOfDistanceEnum">
    <restriction base="string">
      <enumeration value="meters" />
      <enumeration value="inches" />
      <enumeration value="miles" />
    </restriction>
  </simpleType>

**Comment by Amin-Tajgardoon** [comment]
submitted pull request #68.
Supports circle by XY coordinate and radius. Z is not supported.
