### ISSUE TITLE
Typos in API Documentation

### ISSUE THREAD

**Issue by adamdarr** [midas-isg/ls#77]
> Implementation Notes
> Receives a single query as shown in the example.
> Note:
> In version 1, response is not a valid geoJSON ('geometry' property is removed from FeatureCollection response).
> In version 1, properties.children is excluded from features.
> As of version 2, Use _onlyFeatureFields or _excludedFeatureFields for filtering fields.
> As of version 2, request filter-key names changed: 'includeOnly' -> 'onlyFeatureFields' & 'exclude' -> 'excludedFeatureFields'.
> As of version 2, request filter syntax changed. Refer to find-by-term-v2.jsonAs of version 2, "verbose" option is not suppoerted. Use "_onlyFeatureFields":"properties.gid" for non-verbose results.

I didn't look through the whole page but this is just one example (http://betaweb.rods.pitt.edu/ls/api-docs#!/api%2Flocations/Find).

**Comment by Amin-Tajgardoon** [comment]
Fixed in pull-request: #92
